spring:
  datasource:
    username: postgres
    password: Tsunami9
    driverClassName: org.postgresql.Driver
    driverDialect: org.hibernate.dialect.PostgreSQL82Dialect
    url: jdbc:postgresql://localhost/chat_service_db
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog-master.xml

  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
      bindings:
        kafka:
          binder:
            headers: version, action, EventVersion, EntityVersion
        user-event-output:
          destination: user-event
          contentType: application/json
          producer:
            headerMode: raw
server:
  port: 8087

redis:
  host: 127.0.0.1

logging:
   level:
       ROOT: ERROR
       org.springframework.web: ERROR
       com.infopulse: TRACE
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
   file: /home/galkin/application.log



